"""
Constants for easier reference
""" 

NLTK_DATA_PATH = 'pretrained_models/nltk'
TOKENIZER_TEXTBLOB = 'TOKENIZER_TEXTBLOB'
TOKENIZER_NLTK = 'TOKENIZER_NLTK'
TOKENIZER_REGEX = 'TOKENIZER_REGEX'
TOKENIZER_TWITTER = 'TOKENIZER_TWITTER'
TOKENIZER_STANFORD_NLP = 'TOKENIZER_STANFORD_NLP'
TOKENIZER_TAB = 'TOKENIZER_TAB'
TOKENIZER_SPECIAL_DELIMITER = 'TOKENIZER_SPECIAL_DELIMITER'
TOKENIZER_SPACE = ' '

TRAIN_INDEX = 0
VAL_INDEX = 1
TEST_INDEX = 2

TRAIN_MODE = 0
TEST_MODE = 1

MODEL_TYPE_LANGUAGE_MODEL = 'MODEL_TYPE_LANGUAGE_MODEL'

WORD_LEVEL = 'WORD_LEVEL'
CHAR_LEVEL = 'CHAR_LEVEL'
WORD_CHAR_LEVEL = 'WORD_CHAR_LEVEL' #Word embeddings with char. lvl lstms
WORD_HASHING_LEVEL = 'WORD_HASHING_LEVEL'
WORD_HASHING_CONSTANT = '%'

DATASET_TRAIN = 'DATASET_TRAIN'
DATASET_TEST = 'DATASET_TEST'
DATASET_VALIDATION = 'DATASET_VALIDATION'

GPU_MODE = 'GPU_MODE'
CPU_MODE = 'CPU_MODE'

PREPROCESS_TYPE_INCEPTION = 'PREPROCESS_TYPE_INCEPTION'
PREPROCESS_TYPE_GOOGLENET = 'PREPROCESS_TYPE_GOOGLENET'
PREPROCESS_TYPE_RESNET = 'PREPROCESS_TYPE_RESNET'

PREPROCESS_TYPE_RESNET_50 = 'PREPROCESS_TYPE_RESNET_50'
PREPROCESS_TYPE_RESNET_101 = 'PREPROCESS_TYPE_RESNET_101'
PREPROCESS_TYPE_RESNET_152 = 'PREPROCESS_TYPE_RESNET_152'

NETWORK_TYPE_INCEPTION = 'NETWORK_TYPE_INCEPTION'
NETWORK_TYPE_GOOGLENET = 'NETWORK_TYPE_GOOGLENET'
NETWORK_TYPE_RESNET = 'NETWORK_TYPE_RESNET'

NETWORK_TYPE_RESNET_30 = 'NETWORK_TYPE_RESNET_30'
NETWORK_TYPE_RESNET_50 = 'NETWORK_TYPE_RESNET_50'
NETWORK_TYPE_RESNET_101 = 'NETWORK_TYPE_RESNET_101'
NETWORK_TYPE_RESNET_152 = 'NETWORK_TYPE_RESNET_152'

OPTIMIZER_RMSPROP = 'OPTIMIZER_RMSPROP'
OPTIMIZER_ADAM = 'OPTIMIZER_ADAM'
OPTIMIZER_SGD = 'OPTIMIZER_SGD'

# Initializer for weights (zero, uniform and random)
INITIALIZER_ZERO = 'INITIALIZER_ZERO'
INITIALIZER_UNIFORM_RANDOM = 'INITIALIZER_UNIFORM_RANDOM'

# To load vocab things
PATH_NPY_ARRAY = 'PATH_NPY_ARRAY'
PATH_TEXT_ARRAY = 'PATH_TEXT_ARRAY'

# For card types
PREDICTOR_TEXT_FIELD = 'TEXT_FIELD_PREDICTOR'
PREDICTOR_SINGULAR_FIELD = 'SINGULAR_FIELD_PREDICTOR'
PREDICTOR_CHARACTER = 'CHARACTER_PREDICTOR'
